# HTTP server block (redirect all to HTTPS)
server {
    if ($host = support.oqens.me) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = auth2.oqens.me) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = auth.oqens.me) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = host.support.oqens.me) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name echo.oqens.me host.echo.oqens.me dl.oqens.me status.echo.oqens.me host.support.oqens.me support.oqens.me auth.oqens.me auth2.oqens.me;
    return 301 https://$host$request_uri;








}

# Main Portal HTTPS block
server {
    listen 443 ssl;
    server_name echo.oqens.me host.echo.oqens.me dl.oqens.me support.oqens.me auth.oqens.me auth2.oqens.me;
    ssl_certificate /etc/letsencrypt/live/host.support.oqens.me/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/host.support.oqens.me/privkey.pem; # managed by Certbot

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }



}

# Support Portal HTTPS block
server {
    listen 443 ssl;
    server_name host.support.oqens.me;
    ssl_certificate /etc/letsencrypt/live/host.support.oqens.me/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/host.support.oqens.me/privkey.pem; # managed by Certbot


    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }


}

# Status Page HTTPS block
server {
    listen 443 ssl;
    server_name status.echo.oqens.me;

    ssl_certificate /etc/letsencrypt/live/echo.oqens.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/echo.oqens.me/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Payments Portal HTTP block (temporary for Certbot setup)
server {
    listen 80;
    server_name payments.oqens.me;

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

